### ISSUE TITLE
Add more meta tags

### ISSUE THREAD

**Issue by adithyapaib** [Harshita248/PersonalPortfolio#4]
Add more meta tags,
which make it more seo friendly and add more ui improvements
I can do it for you

**Comment by Harshita248** [comment]
Okay right @adithyapaib .Please do it asap.

**Comment by geeks5551** [comment]
Can Add more meta tags, and other ui/ux improvements?

**Comment by charchitmangal** [comment]
Hello! I checked this project and found interesting, pls assign it it to me. I will help you with Meta Tags😄
